### ISSUE TITLE
Feature Request: Allow cookies and logins to be saved

### ISSUE THREAD

**Issue by trymeouteh** [tobykurien/WebApps#132] opened 2019-03-09 06:30 UTC
Please add an option per app to save cookies and password logins. I want to use WebAppss for many forums and do not want to have to login all the time. Also for YouTube I perfer to have autoplay disabled and would like it if the browser will save it and not clear it when I exit the webapp.

**Comment by tobykurien** [comment] 2019-03-19 06:13
Duplicate of #98

**Closed by tobykurien** 2019-03-19 06:13 UTC
