### ISSUE TITLE
Allow HTTP WebApps

### ISSUE THREAD

**Issue by AltNico** [tobykurien/WebApps#42] opened 2016-03-30 09:23 UTC
When the preference "Block insecure requests" is disabled, the user should be able to choose the protocol on its own.

**Comment by tobykurien** [comment] 2016-03-30 10:03
The "block insecure requests" is for 3rd party requests, not for top-level web apps. Infact I think it's a bad idea to have this option, as it potentially removes a critical security feature of WebApps. 

Thankfully, usage of HTTPS is rising (thanks to letsencrypt), so hopefully this will be less of an issue over time. Please urge the websites you want to use to implement HTTPS.

**Comment by tobykurien** [comment] 2016-03-30 10:06
BTW, duplicate of #16 - let's discuss there if you feel that there is good reason to allow HTTP.

**Closed by tobykurien** 2016-03-30 10:06 UTC
